name: Rebuild & push images
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable

permissions:
  contents: read

jobs:
  build-and-push:
    # To not run in forks
    if: github.repository_owner == 'packit'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: files/docker/Dockerfile
            image: packit-service
          - dockerfile: files/docker/Dockerfile.worker
            image: packit-worker
          - dockerfile: files/docker/Dockerfile.tests
            image: packit-service-tests

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Extract branch name and set tag
        shell: bash
        run: |
          branch=${GITHUB_REF#refs/heads/}
          tag=""
          case $branch in
              main)
                  tag="stg latest"
                  ;;
              stable)
                  tag="prod"
                  ;;
          esac
          echo "branch=${branch}" >> $GITHUB_OUTPUT
          unique_tag="${branch}-${GITHUB_SHA::7}-$(date +%s)"
          echo "tag=${tag} ${unique_tag}" >> $GITHUB_OUTPUT
        id: branch_tag

      - name: Build Image
        id: build-image
        # https://github.com/marketplace/actions/buildah-build
        uses: redhat-actions/buildah-build@b4dc19b4ba891854660ab1f88a097d45aa158f76 # v2.12
        with:
          dockerfiles: ${{ matrix.dockerfile }}
          image: ${{ matrix.image }}
          tags: ${{ steps.branch_tag.outputs.tag }}
          # Uncomment once we stop using oc cluster up for tests
          #           oci: true
          build-args: |
            SOURCE_BRANCH=${{ steps.branch_tag.outputs.branch }}

      - name: Push To Quay
        # https://github.com/marketplace/actions/push-to-registry
        uses: redhat-actions/push-to-registry@9986a6552bc4571882a4a67e016b17361412b4df # v2.7.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/packit
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}
